# Generated by Django 4.2.11 on 2026-05-07 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "__first__"),
        ("classes", "0002_semester"),
        ("departments", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("student_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("password", models.CharField(blank=True, max_length=255)),
                ("is_registered", models.BooleanField(default=False)),
                (
                    "parent_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "parent_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "parent_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("preferred_language", models.CharField(default="en", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="classes.class",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "db_table": "api_student",
            },
        ),
    ]
