from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dashboard import page_views

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('api/auth/', include('authentication.urls')),
    path('api/departments/', include('departments.urls')),
    path('api/classes/', include('classes.urls')),
    path('api/subjects/', include('subjects.urls')),
    path('api/students/', include('students.urls')),
    path('api/teachers/', include('teachers.urls')),
    path('api/attendance/', include('attendance.urls')),
    path('api/timetable/', include('timetable.urls')),
    path('api/notifications/', include('notifications.urls')),
    path('api/reports/', include('reports.urls')),
    path('api/stats/', include('dashboard.urls')),
    path('api/student/', include('dashboard.urls')),
    path('api/', include('utils.urls')),

    # Frontend UI routes
    path('', page_views.redirect_root),
    path('login/', page_views.admin_login_page),
    path('admin/register/', page_views.admin_register_page),
    path('admin/forgot-password/', page_views.admin_forgot_page),
    path('admin/reset-password/', page_views.reset_password_page),
    path('logout/', page_views.logout_page),
    path('teacher/login/', page_views.teacher_login_page),
    path('teacher/register/', page_views.teacher_register_page),
    path('teacher/forgot-password/', page_views.teacher_forgot_page),
    path('teacher/reset-password/', page_views.reset_password_page),
    path('student/login/', page_views.student_login_page),
    path('student/register/', page_views.student_register_page),
    path('student/forgot-password/', page_views.student_forgot_page),
    path('student/reset-password/', page_views.reset_password_page),
    path('admin-dashboard/', page_views.admin_dashboard_page),
    path('admin/departments/', page_views.departments_page),
    path('admin/classes/', page_views.classes_page),
    path('admin/subjects/', page_views.subjects_page),
    path('admin/teachers/', page_views.teachers_page),
    path('admin/students/', page_views.students_page),
    path('admin/students/upload/', page_views.upload_students_page),
    path('admin/students/<str:student_id>/', page_views.admin_student_detail_page),
    path('admin/timetable/', page_views.admin_timetable_page),
    path('admin/holidays/', page_views.holidays_page),
    path('admin/reports/', page_views.reports_page),
    path('admin/notifications/', page_views.notifications_page),
    path('teacher/dashboard/', page_views.teacher_dashboard_page),
    path('teacher/mark-attendance/', page_views.mark_attendance_page),
    path('teacher/edit-attendance/', page_views.edit_attendance_page),
    path('teacher/attendance-percentage/', page_views.teacher_percentage_page),
    path('teacher/timetable/', page_views.teacher_timetable_page),
    path('teacher/notifications/', page_views.teacher_notifications_page),
    path('teacher/students/', page_views.teacher_students_page),
    path('teacher/students/<str:student_id>/', page_views.student_detail_page),
    path('student/dashboard/', page_views.student_dashboard_page),
    path('student/attendance/', page_views.student_attendance_page),
    path('student/attendance-percentage/', page_views.student_percentage_page),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
