# Generated by Django 4.2.11 on 2026-05-02 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_semester"),
        ("subjects", "0002_subject_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="assigned_class",
        ),
        migrations.AlterField(
            model_name="subject",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="classes.semester",
            ),
        ),
    ]
