# Generated by Django 4.2.30 on 2026-05-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='My College', max_length=200)),
                ('college_logo', models.ImageField(blank=True, null=True, upload_to='college/')),
                ('principal_name', models.CharField(blank=True, max_length=150)),
                ('college_address', models.TextField(blank=True)),
                ('academic_year', models.CharField(default='2025-2026', max_length=20)),
                ('semester', models.CharField(default='Even Semester', max_length=50)),
                ('min_attendance_percent', models.IntegerField(default=75)),
                ('auto_send_alerts', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'db_table': 'api_systemsettings',
            },
        ),
    ]
