# Generated by Django 4.2.11 on 2026-05-07 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0003_remove_subject_assigned_class_alter_subject_semester"),
        ("students", "0002_normalize_parent_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "parent_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "student_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "subject_names",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "semester_info",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "attendance_percent",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("call_sid", models.CharField(blank=True, default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        default="FAILED",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("tts_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "api_voicecalllog",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("date", models.DateField()),
                ("status", models.CharField(default="SENT", max_length=10)),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("class_id", models.IntegerField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "db_table": "api_notificationlog",
            },
        ),
    ]
