# Generated by Django 4.2.11 on 2026-05-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "parent_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "student_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "subject_names",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "semester_info",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("message", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        default="FAILED",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "api_whatsapplog",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="VoiceCallLog",
        ),
    ]
