# Generated by Django 4.2.11 on 2026-05-02 19:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "__first__"),
        ("teachers", "__first__"),
        ("subjects", "0003_remove_subject_assigned_class_alter_subject_semester"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "api_holiday",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("time", models.TimeField(blank=True, null=True)),
                ("is_present", models.BooleanField(default=False)),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="teachers.teacher",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "db_table": "api_attendance",
                "indexes": [
                    models.Index(
                        fields=["student", "date"],
                        name="api_attenda_student_983d64_idx",
                    ),
                    models.Index(
                        fields=["subject", "date"],
                        name="api_attenda_subject_869fdc_idx",
                    ),
                ],
                "unique_together": {("student", "subject", "date")},
            },
        ),
    ]
