# Generated by Django 4.2.11 on 2026-05-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_normalize_parent_phone"),
        ("subjects", "0003_remove_subject_assigned_class_alter_subject_semester"),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="attendance",
            name="period_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "subject", "date", "period_number")},
        ),
    ]
